#!/usr/bin/env bash
set -e

# move VS code extensions directory into capsule, so they persist across rebuilds
# (this may cause issues on the first run that will be solved by reloading VS code
# if extensions continue to have issues, try commenting out these lines)
echo "mkdir -p /root/capsule/.vscode/extensions" >> /root/.profile
ln -s /root/capsule/.vscode /.vscode

# install updated version of code-server
VERSION=4.93.1
mkdir /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xvz
ln -s /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -

pip install git+https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-basic-analysis.git@main --ignore-installed ruamel.yaml

pip install git+https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-data-utils.git@main --ignore-installed ruamel.yaml